/* eslint-disable eol-last */
export default {
    'zh-CN': {
        merStore: '商户门店',
        storeMan: '店铺管理',
        barMan: '吧台管理',
        merDishes: '商户菜品',
        menuInfo: '菜单信息',
        goodInfo: '商品信息',
        goodDetail: '商品详情',
        home: '首页',
        orderMan: '订单管理',
        orderInfo: '订单信息',
        titlePlate: {
            pcName: '星巴克管理后台',
            testStore: '星巴克体验店',
            logout: '退出'
        },
        orderPlate: {
            orderInfo: '订单信息',
            inputOne: '请输入订单号',
            orderTime: '下单时间',
            // orderDate: '下单日期',
            chooseBar: '选择吧台',
            chooseDate: '选择日期时间',
            chooseTime: '选择时间',
            to: '至',
            orderStatus: '订单状态',
            vaildOrder: '有效',
            invaildOrder: '无效',
            startSearch: '开始查询',
            orderNum: '订单编号',
            barNum: '吧台编号',
            goodName: '商品名称',
            payNum: '支付金额',
            payWay: '支付方式'
        },
        goodsDetail: {
            baseInfo: '基础信息',
            goodsName: '商品名称',
            SKU: '商品SKU',
            goodsType: '商品分类',
            goodsLabel: '商品标签',
            originOfGoods: '商品产地',
            vendorCode: '供应商编码',
            tabOne: '规格信息',
            tabTwo: '加料信息',
            feeding: '加料',
            feddingName: '加料名称',
            tabSKU: 'SKU值',
            price: '价格',
            trTip: '暂无加料信息',
            noSpecTip: '暂无规格信息'
        },
        menuPage: {
            recodShopName: '推荐商品',
            editMenuCN: '编辑菜单',
            addMenuCN: '添加菜单',
            addDifMenuCN: '不能添加重复的菜单名',
            editMenuBigCN: '编辑菜单',
            editMenuExistCN: '输入的菜单名已存在，换一个名字试试吧',
            addMenuBigCN: '添加菜单',
            setTimeCN: '可售时间',
            setTotalCN: '共',
            setVarietiesCN: '种',
            addCategoryCN: '添加分类',
            addCategoryCN1: '添加类别',
            addDifCategoryCN: '不能添加重复的分类名',
            editCategoryExistCN: '输入的分类名已存在，换一个名字试试吧',
            addDifCategoryCN1: '不能添加重复的类别名',
            editCategoryExistCN1: '输入的类别名已存在，换一个名字试试吧',
            okCN: '确定',
            barCounterCN: '所属吧台',
            menuNameCN: '菜单名称',
            InputMenuNameCN: '请输入菜单名称',
            editMenuTypeCN: '编辑菜单分类',
            menuCategoryNameCN: '菜单分类名称',
            InputCategoryNameCN: '请输入菜单分类名称',
            editSellTimeCN: '编辑售卖时间',
            sellDateCN: '售卖日期',
            startDateCN: '开始日期',
            nullOrNoCommitCN: '可空即不做限制',
            sellTimeCN: '售卖时间',
            addMenuTypeCN: '添加菜单分类',
            menuTypeNameCN: '菜单分类名称',
            inputTypeNameCN: '请输入菜单分类名称',
            addMenuTypeCN1: '添加菜单类别',
            menuTypeNameCN1: '菜单类别名称',
            inputTypeNameCN1: '请输入菜单类别名称',
            delMenuTitleCN: '删除菜单',
            delMenuContentCN: '门店菜单下可能存在商品，你确定继续删除？',
            delCateGoryTitleCN: '删除菜单分类',
            delCateGoryContentCN: '删除选中分类，会删除选中分类下所有东西，你确定继续删除？',
            delCateGoryTitleCN1: '删除菜单类别',
            delCateGoryContentCN1: '删除选中类别，会删除选中类别下所有东西，你确定继续删除？',
            delMenuSuccessCN: '菜单删除成功',
            delMenuCategoryCn: '菜单分类删除成功',
            noInfoCN: '暂无菜单信息，请点击编辑菜单后，添加菜单！',
            executeCN: '请在点击确定后执行此操作',
            addTypeSuccessCN: '添加菜单分类名称成功',
            editTypeSuccessCN: '修改菜单分类名称成功',
            addTypeSuccessCN1: '添加类别名称成功',
            editTypeSuccessCN1: '修改类别名称成功',
            addMenuSuccessCN: '添加菜单名称成功',
            editMenuSuccessCN: '修改菜单名称成功',
            nullMenuNameCN: '菜单名称不能为空',
            nullMenuTypeCN: '菜单分类名称不能为空',
            nullMenuTypeCN1: '菜单类别名称不能为空',
            codeCN: '编码',
            bindMenuCN: '绑定菜单',
            TieMenuCN: '解绑菜单',
            isSureBindCN: '你确定将当前菜单绑定到该吧台下?',
            isSureTieCN: '你确定解除绑定到该吧台下的当前菜单?',
            bindSuccessCN: '绑定成功',
            tieSuccessCN: '解绑成功',
            removeShopCN: '移除商品',
            removeSuccessCN: '移除成功',
            isSureRemoveCN: '你确定要将该商品从菜单分类中移除？'
        },
        barBack: {
          floorOneCN: '一层',
          floorTwoCN: '二层',
          BussinessStatusCN: '营业状态',
          BussinessTimeCN: '营业时间',
          CurrentMenuCN: '当前菜单',
          addCN: '添加',
          setBarsCN: '吧台设置',
          doBussinesssCN: '营业中',
          inRestCN: '休息中',
          selectTimeCN: '选择时间',
          warningsCN: '这是一条警告的提示',
          defaultMenuCN: '设置吧台默认菜单成功'
        },
        goodsList: {
            goodsMaintenance: '商品维护',
            all: '全部',
            allSelect: '全选',
            addBtn: '添加',
            editBtn: '编辑',
            delBtn: '删除',
            addLabelBtn: '新增标签',
            encode: '编码',
            friendlyTips: '友情提示',
            friendlyTipsText: '请选择商品，再进行选择!',
            okText: '确认',
            noText: '取消',
            up: '上架',
            down: '下架',
            tagName: '标签名',
            tagNameInput: '请输入标签名',
            menu: '菜单',
            tag: '标签',
            addTags: '添加标签',
            goodsSet: '商品设置',
            goodsStatus: '商品状态',
            newGoods: '新增',
            updateGoods: '更新',
            delGoods: '删除',
            newGoodsHint: '您确定添加新商品吗?',
            updateGoodsHint: '您确定更新旧商品信息吗?',
            delGoodsHint: '您确定删除商品吗?',
            inputGoodsName: '请输入商品名',
            addGoodsY: '新增商品成功。',
            addGoodsN: '新增商品失败。',
            updateGoodsY: '商品更新成功。',
            updateGoodsN: '商品更新失败。',
            moveGoodsY: '移除商品成功。',
            moveGoodsN: '移除商品失败。'
        }
    },
    'en-US': {
        merStore: 'merchant stores',
        storeMan: 'stores management',
        barMan: 'bar counter management',
        merDishes: 'merchant dishes',
        menuInfo: 'menu information',
        goodInfo: 'goods information',
        goodDetail: 'good detail',
        home: 'home',
        orderMan: 'orders management',
        orderInfo: 'orders information',
        titlePlate: {
            pcName: 'starbucks Admin background',
            testStore: 'starbucks experience store',
            logout: 'Logout'
        },
        orderPlate: {
            orderInfo: 'order information',
            inputOne: 'please enter order number',
            orderTime: 'order time',
            // orderDate: 'order date',
            chooseBar: 'choose bar',
            chooseDate: 'choose date time',
            chooseTime: 'choose time',
            to: 'to',
            orderStatus: 'status',
            vaildOrder: 'vaild',
            invaildOrder: 'invaild',
            startSearch: 'start search',
            orderNum: 'order number',
            barNum: 'bar num',
            goodName: 'goods name',
            payNum: 'pay amount',
            payWay: 'pay way'
        },
        goodsDetail: {
            baseInfo: 'Basic information',
            goodsName: 'commodity name',
            SKU: 'commodity S K U',
            goodsType: 'commodity classification',
            goodsLabel: 'commodity label ',
            originOfGoods: 'commodity origin ',
            vendorCode: 'Vendor code',
            tabOne: 'specification information',
            tabTwo: 'feeding information',
            feeding: 'feeding',
            feddingName: 'feeding name',
            tabSKU: 'SKU',
            price: 'price',
            trTip: 'No Feeding information',
            noSpecTip: 'No specification information'
        },
        menuPage: {
          recodShopName: 'Recommending Commodities',
          editMenuCN: 'edit menu',
          addMenuCN: 'add menu',
          addDifMenuCN: 'Duplicate menu name cannot be added',
          editMenuBigCN: 'Edit menu',
          editMenuExistCN: 'The menu name entered already exists. Try another name',
          addMenuBigCN: 'Add menu',
          setTimeCN: 'Time available for sale',
          setTotalCN: 'Total',
          setVarietiesCN: 'varieties',
          addCategoryCN: 'Add categories',
          addCategoryCN1: 'Add class',
          addDifCategoryCN: 'Duplicate name categories cannot be added',
          editCategoryExistCN: 'The name of the entry already exists. Try another name',
          addDifCategoryCN1: 'You cannot add duplicate class aliases',
          editCategoryExistCN1: 'The input class name already exists. Try another name',
          okCN: 'OK',
          barCounterCN: 'Bar counter',
          menuNameCN: 'Menu name',
          InputMenuNameCN: 'Please enter a menu name',
          editMenuTypeCN: 'Edit menu categories',
          menuCategoryNameCN: 'Menu category name',
          InputCategoryNameCN: 'Please enter the menu category name',
          editSellTimeCN: 'Edit selling time',
          sellDateCN: 'Date of sale',
          startDateCN: 'Start date',
          nullOrNoCommitCN: 'Can be empty, that is, no restrictions',
          sellTimeCN: 'Selling time',
          addMenuTypeCN: 'Add menu category',
          menuTypeNameCN: 'Menu class name',
          inputTypeNameCN: 'Please enter the menu category name',
          delMenuTitleCN: 'Delete menu',
          delMenuContentCN: 'There may be items under the store menu. Are you sure you want to continue deleting them?',
          delCateGoryTitleCN: 'Delete menu categories',
          delCateGoryContentCN: 'Deleting the selected category will delete everything under the selected category. Are you sure you want to continue deleting?',
          delMenuSuccessCN: 'Delete the menu successfully',
          delMenuCategoryCn: 'Menu classification deletion success',
          noInfoCN: 'There is no menu information. Please click the edit menu to add menu!',
          addTypeSuccessCN: 'Added menu category name success',
          editTypeSuccessCN: 'Modify menu category name success',
          addTypeSuccessCN1: 'Add category name success',
          editTypeSuccessCN1: 'Modify class name success',
          addMenuSuccessCN: 'Added menu name success',
          editMenuSuccessCN: 'Modify the menu name successfully',
          nullMenuNameCN: 'Menu name cannot be empty',
          nullMenuTypeCN: 'Menu category name cannot be empty',
          nullMenuTypeCN1: 'The menu class name cannot be empty',
          codeCN: 'code',
          bindMenuCN: 'Bind menu',
          TieMenuCN: 'Tie menu',
          isSureBindCN: 'Are you sure you want to bind the current menu to the bar?',
          isSureTieCN: 'Are you sure you want to cancel the current menu that is bound to this bar?',
          bindSuccessCN: 'Bind successfully',
          tieSuccessCN: 'Tie up successfully',
          removeShopCN: 'Remove commodity',
          removeSuccessCN: 'Remove successfully',
          isSureRemoveCN: 'Are you sure you want to remove this item from the menu category?'
        },
        barBack: {
          floorOneCN: 'First Floor',
          floorTwoCN: 'Second Floor',
          BussinessStatusCN: 'Status',
          BussinessTimeCN: 'Times',
          CurrentMenuCN: 'Menu',
          addCN: 'add',
          setBarsCN: 'Bar settings',
          doBussinesssCN: 'In business',
          inRestCN: 'In rest',
          selectTimeCN: 'Selection time',
          warningsCN: 'This is a warning tip',
          defaultMenuCN: 'Set the bar default menu successfully'
        },
        goodsList: {
            goodsMaintenance: 'Goods maintenance',
            all: 'All',
            allSelect: 'Check all',
            addBtn: 'Add',
            editBtn: 'Edit',
            delBtn: 'Del',
            addLabelBtn: 'New tag',
            encode: 'Encode',
            friendlyTips: 'Friendly reminder',
            friendlyTipsText: 'Please select the goods and choose again!',
            okText: 'OK',
            up: 'Up',
            down: 'Down',
            tagName: 'Tag name',
            tagNameInput: 'Please enter the tag name',
            menu: 'Menu',
            tag: 'Tag',
            addTags: 'Add Tags',
            goodsSet: 'Goods set',
            goodsStatus: 'Goods status',
            newGoods: 'New',
            updateGoods: 'Update',
            delGoods: 'Delete',
            newGoodsHint: 'Are you sure to add new products?',
            updateGoodsHint: 'Are you sure to update the old product information?',
            delGoodsHint: 'Are you sure to remove the goods??',
            inputGoodsName: 'Please enter the name',
            addGoodsY: 'New product success.',
            addGoodsN: 'New products fail.',
            updateGoodsY: 'The product was updated successfully.',
            updateGoodsN: 'The commodity update failed.',
            moveGoodsY: 'Remove product success.',
            moveGoodsN: 'Remove failed products.'
        }
    }
};
